api/src/Entity/ClinicalCase.php
api/src/Entity/Symptome.php
api/src/Repository/SymptomeRepository.php

Création de la classe symptôme avec la relation ManyToMany avec les cas cliniques

add entity symptome

---

api/src/Entity/CategoriePathologie.php
api/src/Entity/CategorieTreatment.php
api/src/Entity/ClinicalCase.php
api/src/Entity/Jobs.php
api/src/Entity/Pathologie.php
api/src/Entity/Treatment.php
api/src/Repository/CategoriePathologieRepository.php
api/src/Repository/PathologieRepository.php

Pathology 
Category pathology 

Pathology entity

---

api/src/DataFixtures/AppFixtures.php

add fixtures

---

api/config/packages/lexik_jwt_authentication.yaml

Changer de la durée du Token, passant de 1h à 24h

change token duration 24h

---

api/src/Entity/ClinicalCase.php

Ajout d'une fonction de calcul de moyenne

Add calculate field average

---

api/src/DataFixtures/AppFixtures.php
api/src/Entity/ClinicalCase.php
api/src/Entity/Speciality.php
api/src/Entity/User.php
api/src/Repository/SpecialityRepository.php

In the first time a the speciality entity and add the fixtures
* Hardware:
* Toolchain:
* SDK:

Add the spealisty entity and the fixtures speciality

---

api/src/DataFixtures/AppFixtures.php
api/src/Entity/User.php

Update the user entity, I add the created
* Hardware:
* Toolchain:
* SDK:

Update the user entity

---

api/src/DataFixtures/AppFixtures.php
api/src/Entity/ClinicalCase.php
api/src/Entity/MessageNotification.php
api/src/Entity/Notification.php
api/src/Entity/User.php
api/src/Repository/MessageNotificationRepository.php
api/src/Repository/NotificationRepository.php

Creation of notification and messageNotification entities & fixture
Resolve #47 #46 
* Hardware:
* Toolchain:
* SDK:

Notification & message entities 

---

api/src/DataFixtures/AppFixtures.php
api/src/Entity/ClinicalCase.php

Create slug with title automaticly
Resolve #17 
* Hardware:
* Toolchain:
* SDK:

Slug automatic with title

---

api/src/DataFixtures/AppFixtures.php
api/src/Entity/ClinicalCase.php
api/src/Entity/Keyword.php
api/src/Repository/KeywordRepository.php

keywords entity with the fixtures creation 
Resolve #45 
* Hardware:
* Toolchain:
* SDK:

Keyword entity and fixtures 

---

api/composer.json
api/composer.lock
api/config/bundles.php
api/config/packages/dev/swiftmailer.yaml
api/config/packages/swiftmailer.yaml
api/config/packages/test/swiftmailer.yaml
api/phpunit.xml.dist
api/symfony.lock

Add swiftmailer for send the mail 
Resolve #56 

Add the swiftmailer

---

api/src/Entity/User.php

Recupere les informations de l'utilisateur lors de la recuperation des cas cliniques

Get User Data When We Get ClinicalCase

---

api/src/DataFixtures/AppFixtures.php
api/src/Entity/Commentaire.php
api/src/Entity/Keyword.php
api/src/Entity/User.php
api/symfony.lock

add keyword name to keywords group to see name when api response
* Hardware:
* Toolchain:
* SDK:

Lory rewind user job structure

---

api/src/Entity/Pathologie.php
api/src/Entity/Speciality.php
api/src/Entity/Symptome.php
api/src/Entity/Treatment.php

* Hardware:
* Toolchain:
* SDK:

add name to roups missed

---

api/src/Entity/ImageClinicalCase.php
api/src/Entity/ImageClinicalCaseType.php
api/src/Entity/Jobs.php

Met en relation les jobs avec les cas cliniques et les images lié au cas clinique

Features link job clinicalcase

---

api/src/DataFixtures/AppFixtures.php
api/src/Entity/ImageClinicalCase.php
api/src/Events/ConvertBase64ToImage.php

Modification des fixtures pour les images
Permet l'upload d'image, le client envoie l'image au format base64 et sauvegarde l'image sur le serveur

Fixtures image

---

api/config/services.yaml
api/public/index.php
api/src/Events/JWTCreatedSubscriber.php

Ajout d'attribut lors de la création du JWT

Features JWT

---

api/src/DataFixtures/AppFixtures.php
api/src/Entity/ClinicalCase.php

Resolve #71 
* Hardware:
* Toolchain:
* SDK:

update the clinical case entity

---

api/composer.lock
api/config/packages/doctrine_migrations.yaml
api/symfony.lock
docker/php.Dockerfile

Fixing the docker bug 
Resolve #73 
* Hardware:
* Toolchain:
* SDK:

Fix the docker bug

---

api/src/Entity/CategoriePathologie.php
api/src/Entity/CategorieTreatment.php
api/src/Entity/Pathologie.php
api/src/Entity/Treatment.php
api/symfony.lock

#77 #76 
* Hardware:
* Toolchain:
* SDK:

Group cat-path with path & group cat-treatment with treatment

---

api/src/Entity/Avatar.php
api/src/Entity/User.php
api/src/Repository/AvatarRepository.php

* Hardware:
* Toolchain:
* SDK:

avatar create

---

api/src/Entity/Avatar.php

* Hardware:
* Toolchain:
* SDK:

avatar in group clincal_case

---

api/src/Events/AvatarGeneratorSubscriber.php
api/src/Repository/CategoriePathologieRepository.php
api/src/Repository/ClinicalCaseRepository.php
api/src/Repository/CommentaireRepository.php
api/src/Repository/FavoriteRepository.php
api/src/Repository/ImageClinicalCaseRepository.php
api/src/Repository/ImageClinicalCaseTypeRepository.php
api/src/Repository/JobsRepository.php
api/src/Repository/KeywordRepository.php
api/src/Repository/MessageNotificationRepository.php
api/src/Repository/NotationRepository.php
api/src/Repository/NotificationRepository.php
api/src/Repository/PathologieRepository.php
api/src/Repository/PatientRepository.php
api/src/Repository/SpecialityRepository.php
api/src/Repository/SymptomeRepository.php
api/src/Repository/TreatmentRepository.php
api/src/Repository/UserRepository.php
api/src/Service/AvatarRandom.php

Api in local will work !! Can you try @loryleticee ? ;p
* Hardware:
* Toolchain:
* SDK:

Avatar generate when subsribe And fix Error in all Repo entities

---

.gitignore
api/src/Entity/User.php
api/src/Events/UploadLicenceDocUser.php

Event -> Upload licenceDoc after create user
Firstname & lastname can be null
* Hardware:
* Toolchain:
* SDK:

Inscription user

---

.dockerignore
README.md
docker-compose.yml
docker/php.Dockerfile

When you start the make composer, the php.dockerfile download the composer 2. Many component are not compatible with this version. I'll updating the php.dockerfile and choice the first version.
Resolve #92 

Feature composer version and mariaDB version

---

api/src/DataFixtures/AppFixtures.php
api/src/Entity/Patient.php

* Hardware:
* Toolchain:
* SDK:

Omnipratique

---

api/src/Entity/ImgClinicalCaseOmnipratique.php

Miss the route on the entity clinical case omni, I add the route and fix this missing

route  api clinical case omno

---

api/src/Entity/ImgClinicalCaseOmnipratique.php

* Hardware:
* Toolchain:
* SDK:

add isPrincipal in CC read group

---

Makefile

add the chmod for the jwt config and images for the linux environment

update the makefile

---

.github/workflows/preprod.yaml

add the CD for the pre-production environment
Resolve #100

CD deployment pre-production

---

api/src/Entity/User.php

add clinical case omni on resource api

---

api/src/Entity/Patient.php

Remove the line assertTrue 
Resolve #105

Fix the isSmoker bug

---

api/src/Entity/ClinicalCase.php
api/src/Entity/LogConnexion.php
api/src/Repository/LogConnexionRepository.php

* Hardware:
* Toolchain:
* SDK:

Log connexion new entities done
